# Tab 1: My Project
new_tab BO vim
layout fat
cd ~/Projects/backoffice
launch nvim .

# Tab 2: Logs
new_tab nx run / claude
layout fat
cd ~/Projects/backoffice
launch zsh -l -c 'nx serve backoffice --build-target backoffice:build:development,purplewombat-git; exec zsh'
launch claude

# Tab 3: Home shell
new_tab wake up 
launch cmatrix
